[theme]
# Cor principal (Botões de destaque, barras de carregamento)
primaryColor="#FF4B4B" 

# Cor do fundo da tela inteira (Ex: #0E1117 para um Dark Mode elegante)
backgroundColor="#0E1117" 

# Cor do fundo dos formulários e caixas de texto
secondaryBackgroundColor="#262730" 

# Cor do texto principal
textColor="#FAFAFA" 

# Fonte (opções: "sans serif", "serif", "monospace")
font="sans serif"
